name: Build and deploy staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - main


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  create-tags:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: butlerlogic/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build

  release:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.0
      - name: Setup
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.1
        with:
          REMOTE_PORT: ${{ secrets.SSH_REMOTE_PORT }}
          TARGET: ${{ secrets.SSH_STAGING_TARGET }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_STAGING_PRIVATEKEY }}
          ARGS: "-rltgoDzvO"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.SSH_STAGING_HOST }}
          REMOTE_USER: ${{ secrets.SSH_STAGING_USER }}
          REMOTE_PORT: ${{ secrets.SSH_REMOTE_PORT }}
          TARGET: ${{ secrets.SSH_STAGING_TARGET }}
      - name: Restarting TabT instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_STAGING_HOST }}
          port: ${{ secrets.SSH_REMOTE_PORT }}
          username: ${{ secrets.SSH_STAGING_USER }}
          key: ${{ secrets.SSH_STAGING_PRIVATEKEY }}
          script: cd ${{ secrets.SSH_STAGING_TARGET }} && pm2 reload beping-notifications-pm2.json --env production
